/**
 * Sav Događaji UI copy na jednom mjestu (hrvatski — pilot publika su domaći
 * posjetitelji i organizatori). Ekrani ne smiju sadržavati inline stringove;
 * buduća i18n = zamjena ovog modula. Sentence case.
 */
export const evStrings = {
  tabTitle: 'Događaji',
  hub: {
    title: 'Događaji',
    subtitle: 'Ulaznice izravno od organizatora — bez posrednika i bez naknada.',
    myTickets: 'Moje ulaznice',
    announced: 'Uskoro',
    yourEventHere: 'Tvoj događaj ovdje',
    yourEventHereDesc: 'Organiziraš konferenciju, koncert ili meetup? Prodaja ulaznica bez ijedne naknade.',
  },
  event: {
    share: 'Podijeli događaj',
    tickets: 'Ulaznice',
    aboutOrganizer: 'Organizator',
    date: 'Datum',
    dateTba: 'Termin uskoro',
    venue: 'Lokacija',
    web: 'Web',
    email: 'E-mail',
    notOnchain: 'Ovaj događaj još ne prima plaćanja u aplikaciji.',
    noTiers: 'Prodaja ulaznica još nije počela.',
    buy: 'Kupi',
    saleClosed: 'Prodaja zatvorena',
    named: 'Glasi na ime',
  },
  checkout: {
    title: 'Kupnja ulaznica',
    quantity: 'Broj ulaznica',
    holders: 'Na čije ime glase ulaznice?',
    holderName: 'Ime i prezime',
    holderEmail: 'E-mail (nije obvezno)',
    ticketLabel: 'Ulaznica',
    summary: 'Sažetak',
    total: 'Ukupno',
    pay: 'Plati',
    noActiveAccount: 'Za plaćanje prvo otvori ili uveži račun u aplikaciji.',
    eventInactive: 'Ovaj događaj još ne prima plaćanja u aplikaciji.',
    directNote: 'Plaćaš izravno organizatoru na njegov račun — bez posrednika i bez dodatnih naknada.',
    // Autoritativna odbijanja narudžbe s backenda (strojni kod → poruka).
    orderRejected: {
      tier_sold_out: 'Nažalost, ulaznice u ovoj kategoriji su rasprodane.',
      sale_not_started: 'Prodaja ulaznica u ovoj kategoriji još nije počela.',
      sale_ended: 'Prodaja ulaznica u ovoj kategoriji je završila.',
      holders_incomplete: 'Upiši ime i prezime za svaku ulaznicu.',
      order_rate_limited: 'Previše narudžbi u kratkom vremenu — pokušaj ponovno malo kasnije.',
      amount_mismatch: 'Cijena se u međuvremenu promijenila — osvježi događaj i pokušaj ponovno.',
    } as Record<string, string>,
    orderRejectedFallback: 'Narudžba nije prihvaćena — pokušaj ponovno.',
  },
  tickets: {
    title: 'Moje ulaznice',
    empty: 'Još nemaš ulaznica.',
    reference: 'Referenca',
    status: {
      pending: 'Plaćanje nije dovršeno',
      'paid-unverified': 'Plaćeno — čeka potvrdu organizatora',
      issued: 'Ulaznice izdane',
    },
    ticketState: { issued: 'Vrijedi', checked_in: 'Iskorištena', void: 'Poništena' },
    issuedHeader: 'Ulaznice',
    syncing: 'Provjeravam narudžbe…',
    share: 'Pošalji narudžbu organizatoru',
    shareHint:
      'Nakon plaćanja pošalji organizatoru podatke narudžbe s referencom — ulaznice s QR kodom stižu u aplikaciju s potvrdom uplate.',
    showQr: 'Prikaži QR',
  },
  qr: {
    title: 'Ulaznica',
    holderUnnamed: 'Ulaznica na donositelja',
    hint: 'Pokaži ovaj QR na ulazu. Vrijedi za točno jedan ulazak.',
    notDelivered: 'QR kod ove ulaznice još nije isporučen na ovaj uređaj — osvježi Moje ulaznice uz mrežu.',
    stateNote: { checked_in: 'Ova ulaznica je već iskorištena.', void: 'Ova ulaznica je poništena.' },
  },
  organizer: {
    title: 'Moji događaji',
    notConfigured: 'Ovaj brand nema konfiguriran backend Događaja — organizatorski mod nije dostupan.',
    subtitle: 'Kreiraj event, objavi ga i prodaja kreće — izravno na tvoj račun, bez naknada.',
    loading: 'Učitavam tvoje događaje…',
    unreachable: 'Backend nije dostupan — pokušaj ponovno.',
    retry: 'Pokušaj ponovno',
    empty: 'Još nemaš nijedan događaj.',
    newEvent: 'Novi događaj',
    noOrgAccount: 'Tvoj pristupni token nema administratorski račun organizatora — javi se operateru platforme.',
    openScanner: 'Skener ulaza',
    accountsHeader: 'Računi organizatora',
    allowlisted: 'Objava odobrena',
    notAllowlisted: 'Objava čeka odobrenje operatera',
    dac7Done: 'Podaci organizatora upisani',
    dac7Missing: 'Podaci organizatora (DAC7) nisu upisani — javi se operateru',
    state: { draft: 'Nacrt', active: 'Objavljen', funded: 'Objavljen', closed: 'Zatvoren' } as Record<string, string>,
    // Forma (kreiranje/uređivanje)
    formTitleNew: 'Novi događaj',
    formTitleEdit: 'Uredi događaj',
    fieldTitle: 'Naziv događaja',
    fieldType: 'Vrsta',
    fieldVenueName: 'Mjesto održavanja',
    fieldVenueCity: 'Grad',
    fieldVenueAddress: 'Adresa (nije obvezno)',
    fieldStart: 'Početak (GGGG-MM-DD)',
    fieldEnd: 'Kraj (GGGG-MM-DD)',
    fieldDescription: 'Opis (prikazuje se kupcima)',
    fieldOrganizerEmail: 'Kontakt e-mail za kupce',
    fieldOrganizerWeb: 'Web (nije obvezno)',
    fieldSafe: 'Račun za uplate (Safe adresa)',
    useActiveSafe: 'Upiši adresu ovog računa',
    safeHint:
      'Uplate kupaca idu izravno na ovu adresu — nitko drugi ih ne vidi i ne dira. Bez adrese događaj se ne može objaviti.',
    tiersHeader: 'Kategorije ulaznica',
    tierTitle: 'Naziv kategorije',
    tierPrice: 'Cijena (EUR)',
    tierInventory: 'Broj ulaznica (prazno = neograničeno)',
    tierNamed: 'Glasi na ime',
    tierNamedHint: 'Kupac upisuje ime i prezime za svaku ulaznicu (npr. konferencijska akreditacija).',
    tierLockedNote: 'Cijena i "glasi na ime" su zaključani nakon objave — dodaj novu kategoriju za novu fazu prodaje.',
    addTier: 'Dodaj kategoriju',
    removeTier: 'Ukloni',
    save: 'Spremi',
    saved: 'Spremljeno.',
    // Objava
    publishHeader: 'Objava',
    publish: 'Objavi događaj',
    publishHintNoSafe: 'Za objavu prvo upiši Safe adresu za uplate.',
    publishHintDraft: 'Objavom događaj postaje vidljiv svim korisnicima u Događajima.',
    close: 'Zatvori prodaju',
    closed: 'Prodaja je zatvorena.',
    published: 'Događaj je objavljen — vidljiv je u Događajima.',
    // Promo
    promoHeader: 'Promocija',
    promoHint: 'Podijeli link ili istakni QR na plakatu — otvara događaj u aplikaciji.',
    shareLink: 'Podijeli link',
    // Autoritativna odbijanja (strojni kod → poruka)
    rejected: {
      not_authenticated: 'Pristupni token je istekao ili nije valjan — zatraži novi i spremi ga ponovno.',
      not_authorized: 'Ovaj račun nije administrator organizatora.',
      organizer_not_allowlisted:
        'Objava još nije odobrena za ovog organizatora — javi se operateru platforme (moderacija pilota).',
      campaign_destination_missing: 'Za objavu prvo upiši valjanu Safe adresu za uplate.',
      invalid_destination: 'Safe adresa nije valjana.',
      campaign_destination_locked: 'Adresa za uplate je zaključana nakon prve uplate — javi se operateru.',
      tier_locked: 'Cijena i "glasi na ime" postojeće kategorije su zaključani nakon objave.',
      inventory_below_claimed: 'Broj ulaznica ne može biti manji od već prodanih/rezerviranih.',
      invalid_title: 'Naziv mora imati bar 3 znaka.',
      invalid_venue_name: 'Upiši mjesto održavanja.',
      invalid_venue_city: 'Upiši grad.',
      invalid_tier_title: 'Svaka kategorija mora imati naziv.',
      invalid_tier_price: 'Cijena kategorije nije valjana.',
      invalid_dates: 'Kraj mora biti nakon početka.',
      invalid_state_transition: 'Ova promjena stanja nije moguća.',
      campaign_rate_limited: 'Previše kreiranja u kratkom vremenu — pokušaj kasnije.',
    } as Record<string, string>,
    rejectedFallback: 'Zahtjev odbijen — provjeri podatke i pokušaj ponovno.',
  },
  scanner: {
    title: 'Skener ulaza',
    heading: 'Skeniraj ulaznicu',
    footer: 'Skener za organizatore: uperi kameru u QR ulaznice. Pravo skeniranja provjerava server pri svakom skenu.',
    notConfigured: 'Ovaj brand nema konfiguriran backend Događaja — skener ulaza nije dostupan.',
    tokenTitle: 'Pristup za organizatore',
    tokenHint:
      'Zalijepi pristupni token organizatora (vrijedi ograničeno). Skeniranje je dopušteno samo administratorima organizatorovog računa — provjera je na serveru.',
    tokenPlaceholder: 'Pristupni token',
    tokenSave: 'Spremi token',
    tokenChange: 'Promijeni token',
    invalidFormat: 'Ovo nije QR ulaznice.',
    tryAgain: 'Pokušaj ponovno',
    scanNext: 'Skeniraj sljedeću',
    resultOk: 'Ulaz odobren',
    resultDuplicate: 'Ulaznica je već iskorištena',
    resultVoid: 'Ulaznica je poništena',
    resultNotFound: 'Ulaznica nije pronađena',
    firstEntryAt: 'Prvi ulaz',
    scannedBy: 'Skenirao',
    entryCounter: 'Ulazaka',
    offline: 'Nema mreže — sken nije potvrđen. Ulaz vrijedi tek uz potvrdu servera, pokušaj ponovno.',
    rejected: {
      not_authenticated: 'Pristupni token je istekao ili nije valjan — zatraži novi i spremi ga ponovno.',
      not_authorized: 'Ovaj račun nije administrator organizatora ovog događaja.',
      invalid_token: 'QR kod nije valjan.',
    } as Record<string, string>,
    rejectedFallback: 'Sken odbijen — pokušaj ponovno.',
  },
} as const
