/**
 * Sav Događaji UI copy na jednom mjestu (hrvatski — pilot publika su domaći
 * posjetitelji i organizatori). Ekrani ne smiju sadržavati inline stringove;
 * buduća i18n = zamjena ovog modula. Sentence case.
 */
export const evStrings = {
  tabTitle: 'Događaji',
  hub: {
    title: 'Događaji',
    subtitle: 'Ulaznice izravno od organizatora — bez posrednika i bez naknada.',
    myTickets: 'Moje ulaznice',
    announced: 'Uskoro',
    yourEventHere: 'Tvoj događaj ovdje',
    yourEventHereDesc: 'Organiziraš konferenciju, koncert ili meetup? Prodaja ulaznica bez ijedne naknade.',
  },
  event: {
    tickets: 'Ulaznice',
    aboutOrganizer: 'Organizator',
    date: 'Datum',
    dateTba: 'Termin uskoro',
    venue: 'Lokacija',
    web: 'Web',
    email: 'E-mail',
    notOnchain: 'Ovaj događaj još ne prima plaćanja u aplikaciji.',
    noTiers: 'Prodaja ulaznica još nije počela.',
    buy: 'Kupi',
    saleClosed: 'Prodaja zatvorena',
    named: 'Glasi na ime',
  },
  checkout: {
    title: 'Kupnja ulaznica',
    quantity: 'Broj ulaznica',
    holders: 'Na čije ime glase ulaznice?',
    holderName: 'Ime i prezime',
    holderEmail: 'E-mail (nije obvezno)',
    ticketLabel: 'Ulaznica',
    summary: 'Sažetak',
    total: 'Ukupno',
    pay: 'Plati',
    noActiveAccount: 'Za plaćanje prvo otvori ili uveži račun u aplikaciji.',
    eventInactive: 'Ovaj događaj još ne prima plaćanja u aplikaciji.',
    directNote: 'Plaćaš izravno organizatoru na njegov račun — bez posrednika i bez dodatnih naknada.',
    // Autoritativna odbijanja narudžbe s backenda (strojni kod → poruka).
    orderRejected: {
      tier_sold_out: 'Nažalost, ulaznice u ovoj kategoriji su rasprodane.',
      sale_not_started: 'Prodaja ulaznica u ovoj kategoriji još nije počela.',
      sale_ended: 'Prodaja ulaznica u ovoj kategoriji je završila.',
      holders_incomplete: 'Upiši ime i prezime za svaku ulaznicu.',
      order_rate_limited: 'Previše narudžbi u kratkom vremenu — pokušaj ponovno malo kasnije.',
      amount_mismatch: 'Cijena se u međuvremenu promijenila — osvježi događaj i pokušaj ponovno.',
    } as Record<string, string>,
    orderRejectedFallback: 'Narudžba nije prihvaćena — pokušaj ponovno.',
  },
  tickets: {
    title: 'Moje ulaznice',
    empty: 'Još nemaš ulaznica.',
    reference: 'Referenca',
    status: {
      pending: 'Plaćanje nije dovršeno',
      'paid-unverified': 'Plaćeno — čeka potvrdu organizatora',
      issued: 'Ulaznice izdane',
    },
    ticketState: { issued: 'Vrijedi', checked_in: 'Iskorištena', void: 'Poništena' },
    issuedHeader: 'Ulaznice',
    syncing: 'Provjeravam narudžbe…',
    share: 'Pošalji narudžbu organizatoru',
    shareHint:
      'Nakon plaćanja pošalji organizatoru podatke narudžbe s referencom — ulaznice s QR kodom stižu u aplikaciju s potvrdom uplate.',
    showQr: 'Prikaži QR',
  },
  qr: {
    title: 'Ulaznica',
    holderUnnamed: 'Ulaznica na donositelja',
    hint: 'Pokaži ovaj QR na ulazu. Vrijedi za točno jedan ulazak.',
    notDelivered: 'QR kod ove ulaznice još nije isporučen na ovaj uređaj — osvježi Moje ulaznice uz mrežu.',
    stateNote: { checked_in: 'Ova ulaznica je već iskorištena.', void: 'Ova ulaznica je poništena.' },
  },
  scanner: {
    title: 'Skener ulaza',
    heading: 'Skeniraj ulaznicu',
    footer: 'Skener za organizatore: uperi kameru u QR ulaznice. Pravo skeniranja provjerava server pri svakom skenu.',
    notConfigured: 'Ovaj brand nema konfiguriran backend Događaja — skener ulaza nije dostupan.',
    tokenTitle: 'Pristup za organizatore',
    tokenHint:
      'Zalijepi pristupni token organizatora (vrijedi ograničeno). Skeniranje je dopušteno samo administratorima organizatorovog računa — provjera je na serveru.',
    tokenPlaceholder: 'Pristupni token',
    tokenSave: 'Spremi token',
    tokenChange: 'Promijeni token',
    invalidFormat: 'Ovo nije QR ulaznice.',
    tryAgain: 'Pokušaj ponovno',
    scanNext: 'Skeniraj sljedeću',
    resultOk: 'Ulaz odobren',
    resultDuplicate: 'Ulaznica je već iskorištena',
    resultVoid: 'Ulaznica je poništena',
    resultNotFound: 'Ulaznica nije pronađena',
    firstEntryAt: 'Prvi ulaz',
    scannedBy: 'Skenirao',
    entryCounter: 'Ulazaka',
    offline: 'Nema mreže — sken nije potvrđen. Ulaz vrijedi tek uz potvrdu servera, pokušaj ponovno.',
    rejected: {
      not_authenticated: 'Pristupni token je istekao ili nije valjan — zatraži novi i spremi ga ponovno.',
      not_authorized: 'Ovaj račun nije administrator organizatora ovog događaja.',
      invalid_token: 'QR kod nije valjan.',
    } as Record<string, string>,
    rejectedFallback: 'Sken odbijen — pokušaj ponovno.',
  },
} as const
